site_name: 'Minesweeper game backstage trial'
site_description: 'Main documentation for Backstage features and framework APIs'
repo_url: https://github.com/erensatir/Mine-Sweeper-Game-Java
edit_uri: edit/master/docs

plugins:
  - techdocs-core
  - redirects:
      redirect_maps:
        'index.md': 'overview/what-is-backstage.md'

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Random Title:
      - Random Text: 'docs/index.md'